[workspace]
resolver = "3"
members = ["async-runtime", "domain", "json", "kv", "miniraft", "serde", "util"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
domain = { path = "domain" }
serde = { path = "serde" }
kv = { path = "kv" }
util = { path = "util" }
json = { path = "json" }

[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
cast_possible_truncation = "warn"
dbg_macro = "deny"
indexing_slicing = "deny"
print_stderr = "warn"
print_stdout = "warn"
todo = "warn"
unwrap_used = "deny"
wildcard_imports = "deny"
