[workspace]
resolver = "3"
members = ["raft", "json", "base64", "rand"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"

[workspace.dependencies]
base64 = { path = "base64" }
json = { path = "json" }
raft = { path = "raft" }
rand = { path = "rand" }

[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
cast_possible_truncation = "warn"
dbg_macro = "deny"
indexing_slicing = "deny"
todo = "warn"
unwrap_used = "deny"
wildcard_imports = "deny"
