[workspace]
resolver = "3"
members = ["async-runtime", "domain", "json", "kv", "miniraft", "serde", "util"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
domain = { path = "domain" }
serde = { path = "serde" }
kv = { path = "kv" }
util = { path = "util" }
json = { path = "json" }

[workspace.lints.clippy]
unwrap_used = "deny"
