[package]
name = "raft"
description = "Domain-specific types and associated implementations for the Raft consensus protocol"
version.workspace = true
edition.workspace = true

[dependencies]
json.workspace = true
rand.workspace = true


[lints]
workspace = true

[[bin]]
name = "main-http"
path = "src/main-http.rs"
